/*** THIS FILE IS AUTOMATICALLY GENERATED FROM DtoTemplate.txt TEMPLATE --- DO NOT MODIFY !!! ***/

 

;

// TS Interface for: project.Domain.Dtos.BaseDto
export interface IBaseDto  {
    
    IsDirty: boolean;
}
 
// TS Class for project.Domain.Dtos.BaseDto
export class BaseDto  implements IBaseDto {
        
    IsDirty!: boolean;

    constructor() {        
         
    }
}
