/*** THIS FILE IS AUTOMATICALLY GENERATED FROM DtoTemplate.txt TEMPLATE --- DO NOT MODIFY !!! ***/

 

import { IBaseDto, BaseDto } from "./BaseDto";

// TS Interface for: project.Domain.Dtos.UserInfoDto
export interface IUserInfoDto extends IBaseDto {
    
    Id: number;
    FirstName: string;
    SecondName: string;
}
 
// TS Class for project.Domain.Dtos.UserInfoDto
export class UserInfoDto extends BaseDto implements IUserInfoDto {
        
    Id!: number;
    FirstName!: string;
    SecondName!: string;

    constructor() {        
        super();
    }
}
